### ISSUE TITLE
Marketplace Account UI Improvement

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#1033]
**Summary**
Improve the Marketplace account UI to load each view as complete page.

**Details**
The the pages in account UI are organized to load as single pages with all content including aside menu, header, footer etc.
Espescially with slow network connections and with highly loaded clients this results in annoying slow screen build up. 
When clicking an menu entry in the aside menu the respective view is loaded including all templates. This request is to refactor the UI in a way that the views are decoupled from the surrounding common page framework. 
* The views shall be implementented as composites that are embedded into one single page. 
* By clicking a menu entry in the aside menu, the content shall be loaded with AJAX request and rerendered into the embedding page. 
* Concept hint: In order to reduce this impact of this refactoring, the different existing (sub-)pages shall be preserved. This can be achived by loding the pages with a4j:include and making the menu items to trigger AJAX Requests that only rerender the embedding container of the a4j:include. 
A state of the art replacement with bootsfaces JSF instead of a4j:include is very wellcome but not a must.

**Acceptance criteria**
- [ ] Concept or technical description in this GitLab issue is done an approved. 
- [ ] Sub page contents is loading fast with AJAX. 
- [ ] Only sub page content is rerenders. Header, footer and aside menues stay fix.
- [x] Contained tab views are not jumping on load. 

**Additional context**

**Comment by Piotr-K8i** [comment]
@GoebelL Unfortunately, the attempt to create a page in which only some of its elements would change failed. A lot of errors came out with submiting forms and refreshing info messages.

In task was done:
- Minify css and javascripts
- Unnecessary files transferred from head to body section
- Tomcat is configured to compress files
- Tomcat is configured to allow saving styles, js, images in the cache

What else can be done to speed up page loading:
- [ ] Implement faster DNS resolve
- [ ] Changing the framework [Richfaces weighs a lot compared to other technologies]
- [ ] Removal of bootstrap and put styles inside xhtml files 

**Previous:**
![13.PNG](https://images.zenhubusercontent.com/5e1c60ee5e668415ca9f76d9/da3a97ec-5a73-48c5-888a-ec4196a7c45a)

**At present**
![2.PNG](https://images.zenhubusercontent.com/5e1c60ee5e668415ca9f76d9/bf5957ec-9e89-4ff6-ac5c-8f8297fcd254)

**Comment by GoebelL** [comment]
Hi @KabacinskiPiotr 
I will catch up on the requested Account UI refacoring when I am back from holiday. For the time beeing, performance tuning is ok as long as it's risk less and meaningful. For evidence please add some figures, e.g. page xxx before your change x ms, improved to y ms. 
Changing the UI framework is out of scope. General direction is to get rid from the unmaintained richfaces stuff in the marketplace UI and extend the use bootsfaces instead. Step by step.
