### ISSUE TITLE
Runtime marketplace and Bootstrap customization

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#1204]
**Summary**
This epic contains all tasks that are necessary for the Runtime customization of the OSCM marketplace using the Bootstrap components.

**Details**
List of necessary tasks to be completed.

**Acceptance criteria**
- [ ] Functionality is ok: Toggling scheming works well
- [ ] UI Customizeablitiy is preserved
- [ ] Performance is ok
- [ ] Default schemeing must work as it is

**Additional context**
N/A.

**Comment by GoebelL** [comment]
Done for 19.2.
