### ISSUE TITLE
[Subscription UI] Make the edit subscription views responsive

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#851]
**Summary**
Create responsive edit subscription dialog with bootstrap 

**Details**
Reuse from bootstraptized subscription dialogs that are already existing. See subscription creation and subscription list.

**Acceptance criteria**
- [ ] Unique styling
- [ ] Responsiveness
- [ ] Full width tables with appropriate sized input fields (min width according type of input)
- [ ] Existing logic is reused and unchanged (services and controller part of given MVCs) 
- [ ] Look and large displays
- [ ] Mobile view is fine

**Additional context**
N/A
